
################################################
FROM node:18-slim

RUN apt-get update \
 && apt-get install -y python3 python3-venv python3-pip \
 && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --production

COPY src/ ./src
COPY requirements.txt ./

RUN pip install --upgrade pip \
 && pip install -r requirements.txt

EXPOSE 5000

CMD ["node", "src/server.js"]
