app = "headliner-backend"   # choose or override with your Fly app name

[env]
  # no secrets needed for now

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
